Improved disk space calculation and increased postback timeout
jdleesmiller/writelatex-git-bridge pull request #20
Opened 2016-09-19 09:10 UTC by winstonli

- The postback timeout has been increased to 60s.
- `FSGitRepoStore` uses a `df` equivalent for `.totalSize()`.

I decided not to mock `FSGitRepoStore.totalSize()` because it's bad practice to use partial mocks for code that you own. Instead, we have the option of giving it a strategy for calculating total size.

It defaults to using the equivalent of `df`, whose basic behaviour is tested in `FSGitRepoStoreTest.totalSizeShouldChangeWhenFilesAreCreatedAndDeleted()`. I used a relatively large file (16 Mi) in case of random stuff happening in the os (which we can't really prevent).

In other tests, we use the old `FileUtils.sizeOfDirectory()` so that our results are deterministic.

2016-09-19 10:45 UTC, mmazour commented
Thanks, @winstonli.  Your choices make sense to me.  
Is this still `In progress` or should it be in `Review` at this point?  You're welcome to go ahead and assign to me if the latter.

2016-09-19 17:12 UTC, winstonli commented
Okay, I've done that now.

2016-09-22 12:58 UTC, mmazour commented on src/main/java/uk/ac/ic/wlgitbridge/bridge/repo/FSGitRepoStore.java
> +        this(repoStorePath, d -> d.getTotalSpace() - d.getFreeSpace());
Will this call work, given that the partition we're interested in is:

```
/dev/xvdf      515930552 257808644 231891124  53% /var/git-bridge
```

and git-bridge config says

```
"rootGitDirectory": "/var/git-bridge/git",
```

or do we need to translate `/var/git-bridge/git` to the mount point of its partition `/var/git-bridge` and from there to the partition name `/dev/xvdf` when making this call?

2016-09-22 13:00 UTC, mmazour requested changes
Question about whether we call `getTotalSpace` and `getFreeSpace` with the right value

2016-09-25 11:37 UTC, winstonli commented on src/main/java/uk/ac/ic/wlgitbridge/bridge/repo/FSGitRepoStore.java
> +        this(repoStorePath, d -> d.getTotalSpace() - d.getFreeSpace());
The call uses whatever partition the given File lives on.

From the Java 8 docs (https://docs.oracle.com/javase/8/docs/api/java/io/File.html):

_Instances of this class may or may not denote an actual file-system object such as a file or a directory. If it does denote such an object then that object resides in a partition._

`getTotalSpace()`
_The size, in bytes, of the partition or 0L if this abstract pathname does not name a partition_

`getFreeSpace()`
_The number of unallocated bytes on the partition or 0L if the abstract pathname does not name a partition_

I guess a file "naming" a partition is ambiguous, so I've manually checked that we've got the correct behaviour on Ubuntu 14.04.5 LTS and macOS 10.12.

If it's wrong, the calls will return 0 and the tests (specifically, `FSGitRepoStoreTest.totalSizeShouldChangeWhenFilesAreCreatedAndDeleted()`) will fail.

2016-09-25 19:45 UTC, mmazour approved these changes

2016-09-25 19:45 UTC, mmazour commented
Great.  Thanks, Winston.

(Sorry for the slow reply. Kids kept me really busy today.)

2016-09-28 19:02 UTC, merged

2016-10-10 13:15 UTC, mmazour commented
The thing now is to get this fix, and swapstore, deployed.  I should be able to do it this week.  It'll require a PR on the Ops repo to add the new config settings and put the values into the vault.  @winstonli are you comfortable reviewing Ansible changes, when I have them ready?

2016-10-10 14:24 UTC, jdleesmiller commented
@mmazour If Winston's not available during the week, I can review those ansible changes.