Simple Error Page to Replace Default
jdleesmiller/writelatex-git-bridge pull request #26
Opened 2017-07-14 16:53 UTC by Hugh-OBrien

We had two reports on HackerOne for security problems with using the default Jetty error pages. Quickly summarising:

- Exposes what tech we're using so someone could find a vulnerability based on googling Jetty + version number
- We repeat back whatever anyone puts in the requested url

These are summarised in more detail in [an issue on the main WL repo](https://github.com/overleaf/write_latex/issues/3619)

This instead returns a JSON string with the error code.

It would probably be good to make this configurable in the config file, but being new to this codebase I thought it would be good to plug the security holes rather than wait on me figuring out how to do that.

2017-07-14 21:49 UTC, jdleesmiller requested changes
This seems to work on paths from the root, e.g. `/foo`, but if the path is under the `/api` path, then I still get a default 404 message.

I think that's because it's attached in `initGitHandler`, which comes after the API handler, so the `DefaultHandler` probably handles the request before it gets to the git handler.

I think that `DefaultHandler` may actually want to live in the root rather than in the API handler, and I guess there is somewhere else that we should be attaching this error handler.

As I was poking around, I found out that we can turn off the "Powered by" message in config: Can set _sendServerVersion false in
https://github.com/eclipse/jetty.project/blob/ccf72d6752ca6b3b6f1d7ad28ed0a040592a9597/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java

That might let us override a [method lower down](https://github.com/eclipse/jetty.project/blob/jetty-9.3.11.v20160721/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java#L266) in the chain and keep more of the default behaviour, which does appear to do some useful stuff like set encodings (though I'm not sure how important that is in this context).

WDYT?

2017-07-14 22:20 UTC, jdleesmiller commented
Also: we should probably have some tests. I wrote some return code tests (though I think they could be improved) in https://github.com/overleaf/writelatex-git-bridge/pull/15, and I think we should be able to use a similar approach here.

2017-07-17 11:03 UTC, 40thieves commented
(Sorry accidentally moved the label in waffle)

2017-07-17 11:25 UTC, Hugh-OBrien commented
>I think that's because it's attached in initGitHandler, which comes after the API handler, so the DefaultHandler probably handles the request before it gets to the git handler.

Ah right, yes I see that now.

>I think that DefaultHandler may actually want to live in the root rather than in the API handler, and I guess there is somewhere else that we should be attaching this error handler.

I tried this and it doesn't play well with the git commands etc. You end up with a lot of test failures for all the git commands...

Adding a custom handler to the api causes some 404s to return 500s instead resulting in other test failures. Though I don't see why because we're not changing the response code anywhere.

>As I was poking around, I found out that we can turn off the "Powered by" message in config

I've been looking around in the Jetty docs for where in the server setup to actually set this config and feel like I'm looking in the wrong places.

>That might let us override a method lower down in the chain and keep more of the default behaviour, 

We would still have the issue of the error page sending back whatever was in the url with the alternative default error page? 

I think we'd be better with the simplest error return possible; however I'm not sure I understand how the git part of the git bridge works to do that without breaking things.

2017-09-01 14:52 UTC, mmazour commented
This now handles requests under `/api` as well as `/foo` etc.

Adding tests is still to-do.

2017-09-01 16:02 UTC, mmazour commented
Added tests.

2017-09-05 10:24 UTC, henryoswald approved these changes
It all looks reasonable to me.

2017-09-05 11:45 UTC, jdleesmiller approved these changes
I think this is an improvement, and it addresses the immediate point about informative error pages.

It seems odd to return a 500 on `/foo` --- a 404 seems like a more conventional code for this. If / when we ever get proper error monitoring set up on the git bridge, we may need to revisit this to avoid getting spurious 500 reports.

2017-09-05 12:47 UTC, mmazour commented
Will merge and deploy during low traffic tomorrow morning.

2017-09-06 05:53 UTC, merged