Sk dockerize
jdleesmiller/writelatex-git-bridge pull request #44
Opened 2018-10-25 09:39 UTC by ShaneKilkelly

- Add docker/docker-compose config
- Add a simple makefile to help with running git-bridge

2018-10-26 09:48 UTC, jpallen requested changes
LGTM, but I think we have some redundant things we can remove now this is configured via the dev env?

2018-10-26 09:48 UTC, jpallen commented on README.md
> +## Setup with v2 Dev-Environment
With the changes in the dev-env, I think this is all done automatically now, and so doesn't need including here? Likewise with the OAuth app - the instructions for that should be to run `bin/run rails_v1 rake db:seed` in the dev environment?

2018-10-26 09:48 UTC, jpallen commented on docker-compose.yml
> +version: "3"
I don't think we need this docker-compose file now, since we'll run it from the top-level dev env?

2018-11-06 14:00 UTC, ShaneKilkelly commented
@jpallen up for re-review :+1:

2018-11-06 14:09 UTC, jpallen approved these changes

2018-11-15 09:53 UTC, merged